[build]
  base = "frontent/chat-app"
  publish = "frontent/chat-app/dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"     # 🚀 FIX: Removed the frontent/chat-app prefix from here!
  status = 200
  
  
